apiVersion: v1
kind: Secret
metadata:
      name: metrics-reader-token                     
      namespace: openshift-lightspeed
      annotations:
           kubernetes.io/service-account.name: lightspeed-operator-metrics-reader
type: kubernetes.io/service-account-token
