apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: davecore-thanos-object-storage
      endpoint: s3.us-east-2.amazonaws.com
      insecure: true
      access_key: <ACCESS_KEY HERE>
      secret_key: <SECRET_KEY HERE>
